export const getWord = () => {
 
    const wordsArray = [
        "apple", "grape", "plant", "table", "chair", "ocean", "smile", "beach", "brush", "house",
        "watch", "laugh", "peace", "bread", "music", "heart", "river", "tiger", "horse", "queen",
        "blend", "cloud", "dance", "queen", "chess", "frost", "mango", "olive", "maple", "frost",
        "slide", "stone", "click", "swine", "grass", "light", "frost", "brick", "earth", "horse",
        "solid", "round", "brush", "frost", "blend", "happy", "creek", "space", "dream", "honey",
        "forge", "radio", "plant", "smile", "prism", "amber", "blaze", "cedar", "bloom", "flora",
        "swarm", "cabin", "glide", "flint", "peony", "laugh", "burst", "comet", "shell", "ferns",
        "creek", "stoke", "amber", "green", "glide", "blaze", "bloom", "swarm", "forge", "dance",
        "maple", "river", "olive", "frost", "table", "heart", "brush", "blend", "tiger", "chair",
        "horse", "laugh", "smile", "peach", "beach", "click", "bread", "solid", "light", "queen",
        "flash", "grind", "sleet", "sailor", "crisp", "grill", "cloud", "swamp", "sunny", "coast",
        "truce", "cozy", "skirt", "quilt", "squad", "trend", "sweep", "sharp", "sauce", "wheel",
        "shock", "sugar", "tramp", "creep", "swirl", "quiet", "blend", "drift", "flame", "crown",
        "rider", "swarm", "pouch", "sharp", "plush", "drain", "snare", "fetch", "creed", "route",
        "grain", "spike", "flock", "vivid", "crane", "hound", "glaze", "blitz", "plume", "swish",
        "globe", "roast", "hinge", "flute", "swift", "sworn", "plush", "quilt", "lemon", "stump",
        "cloak", "drift", "quack", "clash", "spare", "sweat", "drown", "swoop", "climb", "mirth",
        "scold", "scout", "shade", "shred", "spout", "grind", "sheep", "thump", "flint", "scoop",
        "smash", "shush", "twist", "greet", "squat", "quash", "whale", "shaky", "slope", "scamp",
        "latch", "fetch", "lunar", "grill", "pride", "wrist", "chill", "frown", "shard", "crisp",
        "wheat", "braid", "craft", "swamp", "scare", "blink", "brisk", "squat", "slink", "cloak",
        "gloss", "flair", "scent", "swell", "sneak", "flung", "crown", "bliss", "brave", "creek",
        "bloom", "greet", "blend", "clash", "grasp", "swine", "drown", "tramp", "truce", "frost",
        "crown", "sweep", "snare", "scold", "fetch", "grain", "prism", "climb", "swish", "spare",
        "scout", "vivid", "graze", "swirl", "shade", "swift", "flame", "clove", "glint", "brave",
        "sworn", "scold", "smash", "spare", "gloss", "swamp", "smirk", "flung", "bliss", "blink",
        "frown", "truce", "scare", "cloak", "frown", "scent", "brisk", "chill", "craft", "drift",
        "scoop", "whale", "spout", "fetch", "twist", "creek", "sweep", "graze", "swift", "shade",
        "sheep", "blink", "pride", "greet", "brave", "scout", "gloss", "sworn", "clove", "flame",
        "climb", "spare", "tramp", "drift", "smash", "scare", "squat", "grind", "plush", "flute",
        "spike", "scamp", "quack", "spout", "swoop", "roast", "scoop", "cloak", "lemon", "plume",
        "hinge", "thump", "blitz", "swift", "clash", "flock", "vivid", "crane", "hound", "glaze",
        "sneak", "blink", "spare", "gloss", "swirl", "shard", "scold", "fetch", "grain", "scare",
        "craft", "drift", "truce", "scent", "grasp", "swamp", "blink", "crown", "squat", "scoop",
        "cloak", "swift", "spout", "smirk", "frown", "brisk", "tramp", "scout", "swoop", "prism",
        "twist", "spike", "spare", "lemon", "quack", "spout", "swoop", "thump", "swift", "hinge",
        "blink", "scold", "gloss", "fetch", "scamp", "blitz", "swine", "drown", "craft", "cloak",
        "pride", "shade", "scare", "greet", "flame", "squat", "spike", "scout", "sheep", "climb",
        "plume", "flock", "cloak", "scent", "grind", "blitz", "craft", "fetch", "whale", "swift",
        "spare", "blink", "scoop", "spout", "scare", "crown", "swoop", "drift", "pride", "brisk",
        "swamp", "greet", "gloss", "clash", "grasp", "scold", "scout", "craft", "scent", "blink",
        "frown", "sheep", "cloak", "spare", "crown", "scare", "swift", "swoop", "fetch", "craft",
        "blink", "scent", "scamp", "sheep", "scout", "swift", "grind", "cloak", "crown", "spout",
        "gloss", "scold", "flock", "scoop", "drift", "plume", "blink", "greet", "squat", "brave",
        "spare", "scare", "prism", "tramp", "swift", "flung", "crown", "sworn", "cloak", "gloss",
        "scold", "smash", "spare", "greet", "scare", "scout", "blink", "swoop", "swift", "scent",
        "scamp", "sheep", "cloak", "craft", "scoop", "drift", "blitz", "blink", "flame", "swift",
        "spare", "climb", "scoop", "swift", "swoop", "greet", "tramp", "cloak", "scare", "blink",
        "scoop", "scent", "scamp", "swift", "grind", "craft", "spout", "drift", "blitz", "cloak",
        "fetch", "scoop", "gloss", "blink", "scare", "scent", "craft", "swift", "spare", "swoop",
        "climb", "pride", "sheep", "greet", "cloak", "scout", "whale", "blitz", "craft", "swift",
        "grind", "swoop", "scoop", "spare", "squat", "gloss", "blink", "scold", "scare", "cloak",
        "swift", "swoop", "flame", "scoop", "fetch", "craft", "drift", "spout", "blink", "greet",
        "scout", "swift", "scamp", "swoop", "grind", "crown", "scent", "blink", "sheep", "swift",
        "prism", "spout", "scoop", "scold", "blink", "gloss", "squat", "cloak", "scent", "craft",
        "scoop", "scare", "swift", "blitz", "greet", "flame", "sheep", "crown", "spout", "scamp",
        "cloak", "scare", "drift", "blink", "gloss", "scoop", "swift", "craft", "swoop", "spare",
        "scout", "fetch", "scold", "greet", "crown", "scent", "cloak", "swift", "blink", "swoop",
        "craft", "sheep", "scare", "prism", "spout", "scoop", "gloss", "blitz", "whale", "swift",
        "scent", "scoop", "blink", "scold", "drift", "flame", "craft", "spare", "squat", "gloss",
        "swift", "scoop", "blitz", "blink", "sheep", "spout", "scamp", "craft", "swoop", "cloak",
        "swift", "squat", "greet", "scoop", "scare", "crown", "whale", "blink", "scent", "swift",
        "pride", "sheep", "scout", "craft", "gloss", "spare", "blitz", "swoop", "scoop", "swift",
        "drift", "scare", "crown", "squat", "whale", "blink", "greet", "scold", "scout", "swoop",
        "cloak", "fetch", "spout", "scoop", "swift", "blitz", "gloss", "scent", "blink", "sheep",
        "scare", "craft", "scoop", "swift", "crown", "whale", "scout", "scold", "swoop", "scent",
        "blitz", "cloak", "greet", "blink", "scoop", "craft", "spare", "sheep", "swift", "drift",
        "crown", "squat", "swoop", "pride", "scare", "scent", "blitz", "greet", "swift", "blink",
        "scold", "sheep", "scoop", "craft", "crown", "whale", "swift"
    ];

    const randomIndex = Math.floor(Math.random() * wordsArray.length);
    let x = wordsArray[randomIndex];
    var charArray = x.split('');
    var upperCaseArray = charArray.map(function(char) {
        return char.toUpperCase();
    });
    return upperCaseArray;
}